prog:main.o minimap.o enigme.o
	gcc main.o minimap.o -o prog -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
main.o:main.c
	gcc -c main.c -g
minimap.o:minimap.c
	gcc -c minimap.c -g
enigme.o:enigme.c
	gcc -c enigme.c -g
