prog:mainfinal.o minimap.o enigme.o integration.o collisionparfaite.o background.o
	gcc mainfinal.o minimap.o enigme.o integration.o collisionparfaite.o background.o -o prog -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
mainfinal.o:mainfinal.c
	gcc -c mainfinal.c -g
minimap.o:minimap.c
	gcc -c minimap.c -g
enigme.o:enigme.c
	gcc -c enigme.c -g
integration.o:integration.c
	gcc -c integration.c -g
background.o:background.c
	gcc -c background.c -g
collisionparfaite.o:collisionparfaite.c
	gcc -c collisionparfaite.c -g
